version: "3"
services:
  nodeapp:
    build: .
    depends_on:
      - postgres
    environment:
      PORT: 8080
      DBUSER: postgres
      DBHOST: postgres
      DBPASSWORD: postgres
    ports:
      - "8080:8080"
  postgres:
    image: postgres:13.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
